[URL Rewrite]
^https?://gd\.10086\.cn/gmccfile/file/image/preloading703/.*.jpg - REJECT
^https?+://clientaccess\.10086\.cn/biz-orange/DN/init/startInit - REJECT-200
^https?+://wap\.js\.10086\.cn/jsmccClient/cd/market_content/api/v\d/market_content\.page\.query - REJECT-200
^https?://app\.10086\.cn/biz-orange/DN/(findSale|homeSale)/getsaleAdver - REJECT
^https?://res\.app\.coc\.10086\.cn/group\d/M00/[0-9]{2}/[A-Z0-9]{2}/.+.jpg - REJECT-200

[MITM]
hostname = %APPEND% gd.10086.cn,clientaccess.10086.cn,wap.js.10086.cn,app.10086.cn,res.app.coc.10086.cn
