#!name=微信读书
#!desc=微信读书自用
#!icon=https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/06/e3/dc/06e3dc48-fba1-59d7-28ed-0fed96cc3ca5/Placeholder.mill/200x200bb-75.png

[URL Rewrite]
^https?://ae\.weixin\.qq\.com - REJECT
^https?://rmonitor\.qq\.com - REJECT
^https?://oss\.weread\.qq\.com - REJECT
^https?://ap-shanghai\.cls\.tencentcs\.com - REJECT

[Script]
微信读书 = type=http-response, script-path=https://raw.githubusercontent.com/ofwh/Profiles/main/Shadowrocket/Scripts/WeRead.js, pattern=^https?:\/\/.*\.weread\.qq\.com\/mobileSync, max-size=131072, requires-body=true, timeout=10, enable=true

[MITM]
hostname = %APPEND% weread.qq.com, i.weread.qq.com, ae.weixin.qq.com, rmonitor.qq.com, oss.weread.qq.com, ap-shanghai.cls.tencentcs.com
